services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=https://eodebwmedqwhufzsvpko.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZGVid21lZHF3aHVzenN2cGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2NTI2MzcsImVxpCI6MjA0ODIyODYzN30.RkbgSmxYhTqVrjKTMgL8bbJGo1xNkG9pfKVZYDHG4uQ
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    command: wait-for-it backend:8080/health --timeout=120 -- npm run dev