-- AlterTable
ALTER TABLE "Driver" ALTER COLUMN "minKm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "tax" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Rating" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION;
